version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:7
    container_name: taskflow-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: taskflow_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - taskflow-dev-network

  # 后端API服务 (开发模式)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: taskflow-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: mongodb://mongodb:27017/taskflow_dev
      JWT_SECRET: dev-secret-key
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:3001
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - taskflow-dev-network
    command: npm run dev

  # 前端应用 (开发模式)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: taskflow-frontend-dev
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:5000/api
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - taskflow-dev-network
    command: npm run dev

volumes:
  mongodb_dev_data:
    driver: local

networks:
  taskflow-dev-network:
    driver: bridge